INSERT INTO case_studies (slug, client_name, industry, summary, challenge, solution, results_md, metrics, status, published_at) VALUES
('grand-venture-technology', 'Grand Venture Technology (GVT)', 'Precision Engineering · SG / MY / CN',
 'High-precision CNC machining and semiconductor assembly across three countries.',
 'High-mix precision machining required multi-site job costing and real-time scrap tracking.',
 'Epicor Kinetic ERP + OpexMX real-time shop floor dispatch and WIP tracking.',
 '-38% costing turnaround\n-99.4% WIP visibility\n-24% floor scrap',
 '[{"label":"Faster Costing","value":"38%"},{"label":"WIP Visibility","value":"99.4%"},{"label":"Floor Scrap","value":"-24%"}]',
 'published', datetime('now')),
('ojj-foods', 'OJJ Foods', 'Food Processing & Cold Chain · Singapore',
 'Automated meat processing and cold storage distribution.',
 'Perishable inventory, variable catch-weights, and strict SFA/HACCP safety compliance.',
 'Epicor ERP + OpexDX catch-weight module with automated barcode lot traceability.',
 '-100% traceability\n-18% cold chain waste\n-2.5x order speed',
 '[{"label":"Traceability","value":"100%"},{"label":"Cold Chain Waste","value":"-18%"},{"label":"Order Speed","value":"2.5x"}]',
 'published', datetime('now')),
('wong-fong-engineering', 'Wong Fong Engineering', 'Heavy Machinery & ETO · Singapore',
 'Mobile cranes and transport equipment manufacturing.',
 'Complex Engineer-to-Order (ETO) multi-tier BOMs and fragmented field service dispatch.',
 'Epicor Advanced Project Management + OpexAssistant for automated ECO workflows.',
 '-30% ETO lead time\n-92% on-time assembly\n-Unified field service',
 '[{"label":"ETO Lead Time","value":"-30%"},{"label":"On-Time Assembly","value":"92%"},{"label":"Field Service","value":"Unified"}]',
 'published', datetime('now')),
('pt-kobexindo-tractors', 'PT Kobexindo Tractors Tbk', 'Heavy Equipment Distribution · Indonesia',
 'Nationwide machinery, parts, and mining logistics.',
 'Spare parts inventory and field maintenance across 10+ nationwide branches and remote mine sites.',
 'Multi-branch Epicor ERP connected via OpexDX middleware for live inventory sync.',
 '-10+ branches synced\n-28% parts stockouts\n-Mining site support',
 '[{"label":"Branches Synced","value":"10+"},{"label":"Parts Stockouts","value":"-28%"},{"label":"Mining Support","value":"Live"}]',
 'published', datetime('now')),
('pt-mf-feed-mills', 'PT MF', 'Animal Feed & Poultry Manufacturing · Indonesia',
 'Nationwide feed milling operation unifying six plants and four connected systems.',
 'Maintenance data scattered across six feed mills; no unified view of work orders and asset history.',
 'OpexMX CMMS rollout across all mills with connected systems and real-time data freshness.',
 '-6 mills unified\n-4 systems connected\n-Real-time data freshness',
 '[{"label":"Feed Mills Unified","value":"6"},{"label":"Connected Systems","value":"4"},{"label":"Data Freshness","value":"Real-time"}]',
 'published', datetime('now')),
('pt-eei-cable', 'PT EEI', 'Cable & Wire Manufacturing · West Java, Indonesia',
 'Cable and wire manufacturing with audit-ready reporting requirements.',
 'Manual reporting could not keep up with ISO 9001 audit requirements and traceability needs.',
 'OpexMX structured work orders and automated audit-ready reporting.',
 '-Minutes to audit-ready reports\n-ISO 9001 standard\n-High manual effort cut',
 '[{"label":"Audit Reports","value":"Minutes"},{"label":"ISO Standard","value":"9001"},{"label":"Manual Effort","value":"Cut High"}]',
 'published', datetime('now')),
('polytron-hartono', 'PT Hartono Istana Teknologi (Polytron)', 'Consumer Electronics Manufacturing · Kudus, Central Java',
 'Consumer electronics manufacturing with 12+ production lines and 50+ maintenance staff.',
 'PM compliance across 12+ production lines managed manually by a 50+ person maintenance team.',
 'OpexMX preventive scheduling and shift-aware assignment across all lines.',
 '-12+ production lines\n-50+ maintenance team\n-Improved PM compliance',
 '[{"label":"Production Lines","value":"12+"},{"label":"Maintenance Team","value":"50+"},{"label":"PM Compliance","value":"Improved"}]',
 'published', datetime('now')),
('pt-trias-sentosa', 'PT Trias Sentosa', 'Flexible Packaging & Film Manufacturing · Tangerang, Banten',
 'Flexible packaging and film manufacturing across multiple sites.',
 'Downtime and maintenance coordination across multiple manufacturing sites.',
 'OpexMX multi-site maintenance visibility and preventive execution.',
 '-Significant downtime reduction\n-40+ maintenance team\n-Multi-site coverage',
 '[{"label":"Manufacturing Sites","value":"Multiple"},{"label":"Maintenance Team","value":"40+"},{"label":"Downtime","value":"Significant Reduction"}]',
 'published', datetime('now'));
